name: pytest allure report


on:
  workflow_dispatch:



concurrency:
  group: pytest
  cancel-in-progress: true


jobs:

  test:

    runs-on: self-hosted


    steps:


    # 拉代码
    - name: Checkout
      uses: actions/checkout@v4



    # 环境检查
    - name: Check Environment
      run: |
        python3 --version
        pip3 --version
        allure --version



    # 安装依赖
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt



    # Playwright
    - name: Install Playwright
      run: |
        playwright install chromium



    # 执行测试
    - name: Run Test
      continue-on-error: true
      run: |
        pytest \
        --alluredir=allure-results



    # 生成报告
    - name: Generate Allure Report
      if: always()
      run: |
        rm -rf reports

        mkdir -p reports

        allure generate \
        allure-results \
        -o reports/allure-report \
        --clean



    # 检查报告
    - name: Check Allure Report
      if: always()
      run: |
        ls -la allure-results || true

        ls -la reports/allure-report



    # 上传
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-report



    # 发布 Pages
    - name: Deploy Allure Report
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports/allure-report
        publish_branch: gh-pages
