name: pytest allure report


on:

  workflow_dispatch:

  push:

    branches:

      - main



concurrency:

  group: pytest

  cancel-in-progress: true



permissions:

  contents: write



jobs:


  test:


    runs-on: self-hosted



    steps:


    # =========================
    # 拉取代码
    # =========================

    - name: Checkout

      uses: actions/checkout@v4



    # =========================
    # Python环境
    # =========================

    - name: Check Python

      run:

        python3 --version

        pip3 --version



    # =========================
    # pip缓存
    # =========================

    - name: Cache pip

      uses: actions/cache@v4

      with:

        path: ~/Library/Caches/pip

        key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

        restore-keys:

          |
          pip-${{ runner.os }}-



    # =========================
    # 安装依赖
    # =========================

    - name: Install dependencies

      run:

        pip3 install -r requirements.txt



    # =========================
    # Playwright
    # =========================

    - name: Install playwright

      run:

        playwright install chromium



    # =========================
    # 执行测试
    # =========================

    - name: Run Test

      continue-on-error: true

      run: |

        chmod +x run.sh

        ./run.sh



    # =========================
    # Allure报告
    # =========================

    - name: Generate Allure Report

      if: always()

      run: |

        mkdir -p reports/allure-report


        allure generate \
        reports/allure-results \
        -o reports/allure-report \
        --clean



    # =========================
    # 测试统计
    # =========================

    - name: Generate Test Summary

      if: always()

      run: |

        python3 utils/allure_summary.py


        cat reports/summary.json



    # =========================
    # 发布GitHub Pages
    # =========================

    - name: Deploy Allure Report

      if: always()

      uses: peaceiris/actions-gh-pages@v4


      with:

        github_token: ${{ secrets.GITHUB_TOKEN }}

        publish_dir: ./reports/allure-report

        publish_branch: gh-pages

        force_orphan: true



    # =========================
    # 保存报告
    # =========================

    - name: Upload Allure Report

      if: always()

      uses: actions/upload-artifact@v4


      with:

        name: allure-report

        path: reports/allure-report



    # =========================
    # 飞书通知
    # =========================

    - name: Send Feishu Message

      if: always()


      env:

        FEISHU_WEBHOOK:

          ${{ secrets.FEISHU_WEBHOOK }}


      run: |

        python3 utils/send_feishu.py
